#pragma config(Motor,   motor1,        wristMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,   motor2,        rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Sensor,  port5,  			 gyro,          sensorVexIQ_Gyro)
#pragma config(Motor,   motor6,        leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,   motor7,        armMotor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,   motor12,       clawMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Function Prototypes
void moveToAimingPosition();
void moveToNeutralPosition();
void moveToLowerStackingPosition();
void moveToUpperStackingPosition();
task displayMyMotorPositions();

//Global Variable & Constant declarations

int const REVERSE_GRIP_ARM = 955, REVERSE_GRIP_WRIST = 460;

int const STACK_BLOCKS_LOW_WRIST = 250, 	STACK_BLOCKS_LOW_ARM = 40;

int const STACK_BLOCKS_HIGH_WRIST = 152, 	STACK_BLOCKS_HIGH_ARM = 243;

float globalArmPosition = 0, globalClawPosition = 0, globalWristPosition = 0;


task main() {

	int leftMotorSpeed, rightMotorSpeed, wristMotorSpeed, armMotorSpeed, stickAValue, stickBValue, stickCValue, stickDValue;

	resetMotorEncoder(armMotor);
	resetMotorEncoder(clawMotor);
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(wristMotor);

	resetGyro(gyro);
	startGyroCalibration(gyro, gyroCalibrateSamples2048);
	eraseDisplay();
	getGyroCalibrationFlag(gyro);
	displayString(3, "calibrating gyro");
	wait1Msec(500);
	eraseDisplay();

	startTask(displayMyMotorPositions);


	while (true ){


		/***************************************************************************************************************/
		//Joystick Control:

		stickAValue  = getJoystickValue(ChA);
		if ((stickAValue <= 15) && (stickAValue >= -15) ) stickAValue = 0;

		stickBValue  = getJoystickValue(ChB);
		if ((stickBValue <= 15) && (stickBValue >= -15) ) stickBValue = 0;

		if (stickBValue >=0 ) 	 	stickBValue = (stickBValue / 10) * (stickBValue / 10) * 2;
		else stickBValue = 		- (stickBValue / 10) * (stickBValue / 10) * 2;



		leftMotorSpeed = stickAValue - stickBValue;
		rightMotorSpeed = stickAValue + stickBValue;

		if ( leftMotorSpeed > 100) leftMotorSpeed = 100;
		if ( leftMotorSpeed < -100) leftMotorSpeed = -100;

		if ( rightMotorSpeed > 100) rightMotorSpeed = 100;
		if ( rightMotorSpeed < -100) rightMotorSpeed = -100;

		if (leftMotorSpeed >=0 ) 	 	leftMotorSpeed = (leftMotorSpeed / 10) * (leftMotorSpeed / 10);
		else leftMotorSpeed = 		- (leftMotorSpeed / 10) * (leftMotorSpeed / 10);
		if (rightMotorSpeed >=0 ) 	rightMotorSpeed = (rightMotorSpeed / 10) * (rightMotorSpeed / 10);
		else rightMotorSpeed = 		- (rightMotorSpeed / 10) * (rightMotorSpeed / 10);

		setMotorSpeed(leftMotor, leftMotorSpeed);
		setMotorSpeed(rightMotor, rightMotorSpeed);


		/***************************************************************************************************************/
		//WRIST MOTOR
		stickDValue		= getJoystickValue(ChD);
		if ((stickDValue <= 15) && (stickDValue >= -15) ) stickDValue = 0;

		wristMotorSpeed = stickDValue;

		if (wristMotorSpeed >=0 ) 	 	wristMotorSpeed = (wristMotorSpeed / 10) * (wristMotorSpeed / 10);
		else wristMotorSpeed = 		- (wristMotorSpeed / 10) * (wristMotorSpeed / 10);


		setMotorSpeed(wristMotor, wristMotorSpeed );


		/***************************************************************************************************************/
		//ARM MOTOR
		stickCValue		= getJoystickValue(ChC);
		if ((stickCValue <= 15) && (stickCValue >= -15) ) stickCValue = 0;

		armMotorSpeed = stickCValue;

		if (armMotorSpeed >=0 ) 	 	armMotorSpeed = (armMotorSpeed / 10) * (armMotorSpeed / 10);
		else armMotorSpeed = 		- (armMotorSpeed / 10) * (armMotorSpeed / 10);

		setMotorSpeed(armMotor, armMotorSpeed );



		/***************************************************************************************************************/
		//CLAW MOTOR
		if(getJoystickValue(BtnLUp) > 0)   {  //CLOSE
			setMotorSpeed(clawMotor, 70);
		}
		else if(getJoystickValue(BtnLDown) > 0)   {  //OPEN
			globalClawPosition = getMotorEncoder(clawMotor);
			if (globalClawPosition <= -89) {
				setMotorTarget(clawMotor, -89, 70);
			}
			else {
				setMotorSpeed(clawMotor, -70);
			}
		}
		else {
			setMotorSpeed(clawMotor, 0);
		}


		/***************************************************************************************************************/
		//Buttons to move our Arm for Us quickly to other positions
		if(getJoystickValue(BtnEUp) > 0)   {  //UP
			moveToAimingPosition();
			wait1Msec(50);
		}
		if(getJoystickValue(BtnEDown) > 0)   {  //GRAB a Block
			moveToNeutralPosition();
			wait1Msec(50);
		}

		/***************************************************************************************************************/
		// Reset button to move the robot back to neutral
		if(getJoystickValue(BtnRUp) > 0)   {
			moveToNeutralPosition();
			wait1Msec(50);
		}

		/***************************************************************************************************************/
		//Block Stacking Positions
		//Buttons to move our Arm for Us quickly to other positions
		if(getJoystickValue(BtnFUp) > 0)   {  //Upper Stacking Position
			moveToUpperStackingPosition();
			wait1Msec(50);
		}
		if(getJoystickValue(BtnFDown) > 0)   {  //Lower Stacking Position
			moveToLowerStackingPosition();
			wait1Msec(50);
		}
	}

}


task displayMyMotorPositions(){

	float clawEncoderValue, wristEncoderValue, armEncoderValue, calibratedGyroDegrees, calibratedGyroHeading;



	while(true) {

		calibratedGyroDegrees = getGyroDegreesFloat(gyro);
		calibratedGyroHeading = getGyroHeadingFloat(gyro);

		clawEncoderValue 		= getMotorEncoder(clawMotor);
		wristEncoderValue 	= getMotorEncoder(wristMotor);
		armEncoderValue 		= getMotorEncoder(armMotor);

		eraseDisplay();
		displayString(0, "claw:  %f3", clawEncoderValue);
		displayString(1, "wrist: %f3", wristEncoderValue);
		displayString(2, "arm:   %f3", armEncoderValue);
		displayString(4, "d: %f3  h: %f3", calibratedGyroDegrees, calibratedGyroHeading);

		wait1Msec(1000);
	}
}

void moveToAimingPosition(){

	int armPowerLevel = 60;
	setMotorTarget(armMotor,  	 REVERSE_GRIP_ARM, 		armPowerLevel);
	setMotorTarget(wristMotor,   REVERSE_GRIP_WRIST , 	armPowerLevel);
}

void moveToNeutralPosition(){

	int armPowerLevel = 60;
	setMotorTarget(armMotor,  	 0, 		armPowerLevel);
	setMotorTarget(wristMotor,   0, 	armPowerLevel);
}

void moveToLowerStackingPosition(){
	int armPowerLevel = 60;
	setMotorTarget(armMotor,  	 STACK_BLOCKS_LOW_ARM, 		armPowerLevel);
	setMotorTarget(wristMotor,   STACK_BLOCKS_LOW_WRIST, 	armPowerLevel);
}

void moveToUpperStackingPosition(){
	int armPowerLevel = 60;
	setMotorTarget(armMotor,  	 STACK_BLOCKS_HIGH_ARM, 		armPowerLevel);
	setMotorTarget(wristMotor,   STACK_BLOCKS_HIGH_WRIST, 	armPowerLevel);
}
